### ISSUE TITLE
Promotion code field missing on payment re-attempt from the front-end link and when only Global promo codes used for event

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/EE4-Promotions#23]
The promotion code field doesn't appear if you use the front-end link from the actions column of the transactions overview screen.

I noticed this on a customer's site and then checked on the demo site for Event Smart:

- Promo code: https://demo.eventsmart.com/wp-admin/admin.php?page=espresso_promotions&action=edit&PRO_ID=1&edit_nonce=0475938710

- Front-end link: https://demo.eventsmart.com/registration-checkout/?uts=1572961351&e_reg_url_link=1-57ce44d8664c52007317f06ac1fc34aa&step=payment_options&revisit=1&clear_session=1#checkout

**Steps to reproduce**
- Set up a promotion and enable for all events
- Go to the transactions screen and then filter to incomplete
- Click on the front-end link

**Other notes**
Customers use this to reduce or zero out the cost of a registration or ticket.

**Comment by joshfeck** [comment]
This appears to be one of the regressions from adding #22 (which isn't released yet, but apparently was released on Eventsmart).

It looks like there are two new issues since the merge:
1) The above issue where the promo code field isn't displayed on a revisit
2) If no promotion codes are assigned to an event (and they use the Global option instead) then promo code field isn't displayed on a regular SPCO transaction

**Comment by joshfeck** [comment]
fixed in #25
