### ISSUE TITLE
Prohibit Duplicate Promotion Codes

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/EE4-Promotions#29]
## Issue Overview

Currently (version 1.0.13.rc.004), you can create multiple promotion codes with the same code. When I tested, the first promotion code is being applied. This should generally be prohibited since it could confuse the system and makes it more difficult to manage codes.

It looks like the first promotion code entered is being applied:

![image](https://user-images.githubusercontent.com/3094547/78810149-341abc00-7985-11ea-9de0-4595bc6da64a.png)
and
![image](https://user-images.githubusercontent.com/3094547/78810171-3e3cba80-7985-11ea-9cc9-ca1e04868401.png)

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 

Version of this addon:

Version of WordPress:

PHP Version:  

Browser used:

**Comment by joshfeck** [comment]
I'm not sure that the same promo code should be prohibited from being added to the system more than once. Some example use cases where prohibiting duplicates could cause some issues:

1) Setting up Event specific codes. Let's say I want to do a promotion called "TAKETWO" and I set up a code "TAKETWO" and assign it to a specific event with a specific expiration date. Then I also want to set up the same code "TAKETWO" for another event (with a different discount amount and a different expiration date). I can do that now, and it just works. If EE starts prohibiting this I can no longer do this.

2) Reusing an old code without having to go in and find and edit the promo code. For example if I ran a promotion 2 years ago that applied to specific events. If I want to run the same promotion again and use the same promo code (because I still have some flyers already printed with the promo code) it'd be a much easier experience to set up a new promotion using the same promo code for the current and upcoming events.
